name: Send Slack Notification

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  send-notification:
    runs-on: ubuntu-latest

    steps:
      - name: Send Slack Notification
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"Hello, new version!"}' https://hooks.slack.com/services/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
