name: Send Slack Notification

on:
  push:
    branches:
      - main

jobs:
  send-notification:
    runs-on: ubuntu-latest

    steps:
      - name: Send Slack Notification
        run: |
          # Your API request to send a message to Slack
          curl -X POST -H "Content-type: application/json" --data '{
            "text": "GitHub Action Notification: A push event just occurred on the main branch."
          }' https://hooks.slack.com/services/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
